Repository scornevi/RepAIr_Capstone_Project, pull requests merged in 2025-04, with the labels that each got.

#63 changed structure of chat_stream script to break down chat_interface …
  chat_logic/chat_stream.py
Labels: Overall tasks

#65 fixed prompt bug and blanked global
  chat_logic/chat_stream.py
  rag/vectorization_functions.py
  research/ifixit_document_retrieval.ipynb
Labels: Overall tasks

#64 ifixit categories to data frame and plots of device counts
  research/categories_2.py
Labels: Overall tasks

#69 60 UI fit interface to browser window clear input text box upon submitting
  ui/custom_css.py
  ui/interface_design.py
Labels: User Interface

#72 43 implement end of chatrestart chat
  chat_logic/chat_stream.py
  ui/interface_design.py
Labels: End of repair and ticket generation

#82 bg colors adjusted, task finished
  ui/custom_css.py
  ui/interface_design.py
Labels: User Interface

#86 mini bug fix
  chat_logic/chat_stream.py
Labels: Overall tasks

#87 prototype for preloading embedding model
  helper_functions/load_embed_model.py
  main.py
  rag/vectorization_functions.py
Labels: Load guides and present repair steps
